name: lint
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/*'
      - '*.md'
      - '*.rst'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/*'
      - '*.md'
      - '*.rst'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Run lint
        run: tox
        env:
          TOXENV: pre-commit
      - name: Run mypy
        run: tox
        env:
          TOXENV: mypy
